### ISSUE TITLE
Can you add a license, please?

### ISSUE THREAD

**Issue by jasam-sheja** [Logrus/BM4D-GPU#2]
Thank you for your fantastic effort in developing and sharing your BM4D code on GitHub. 

Could you kindly consider adding a license to your work? Doing so would significantly enhance the accessibility of your code, allowing more people to use it.

You may find this webpage informative on licenses: [Choose a License](https://choosealicense.com/no-permission/). It offers detailed explanations and guidance on the subject.

Once again, thank you for your exceptional work and for considering this request.

**Comment by Logrus** [comment]
I added a license.
